      - name: Generate trophy.svg (attempt 1)
        id: generate_trophy_first_attempt
        continue-on-error: true
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          output_path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate trophy.svg (retry)
        if: steps.generate_trophy_first_attempt.outcome == 'failure'
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: ${{ github.repository_owner }}
          output_path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
